services:
  web:
    build: .
    container_name: repasse-web
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/app/src
    command: bash -lc "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8001:8000"
    restart: unless-stopped
